### ISSUE TITLE
Add YAML to JSON task

### ISSUE THREAD

**Issue by hhzl** [hhzl/LearnWords2#168]
Example input

````YAML
---
-
    word: lion
    translate: der Löwe
    tags: animal
    picture: c10/lion.jpg
-
    word: hyena
    translate: die Hyäne
    tags: animal
    picture: c10/hyena.jpg
-
    word: goat
    translate: die Ziege
    tags: animal
    picture: c10/goat.jpg
-
    word: hen
    translate: die Henne
    tags: animal
    picture: c10/hen.jpg
-
    word: dog
    translate: der Hund
    tags: animal
    picture: c10/dog.jpg
-
    word: donkey
    translate: der Esel
    tags: animal
    picture: c10/donkey.jpg
-
    word: duck
    translate: die Ente
    tags: animal
    picture: c10/duck.jpg
-
    word: fish
    translate: der Fisch
    tags: animal
    picture: c10/fish.jpg
-
    word: toad
    translate: die Kröte
    tags: animal
    picture: c10/toad.jpg
-
    word: cat
    translate: die Katze
    tags: animal
    picture: c10/cat.jpg
-
    word: rabbit
    translate: der Hase
    tags: animal
    picture: c10/rabbit.jpg
````
