### ISSUE TITLE
npm test: TypeError: object is not a function

### ISSUE THREAD

**Issue by hhzl** [hhzl/LearnWords2#31]
````
Failures:
1) LearnWords2 - App model BoxOfQuestions should be able to create a BoxOfQuestions object
  Message:
    TypeError: object is not a function
  Stack:
    TypeError: object is not a function
        at Object.<anonymous> (/home/user8/Documents/LearnWords2/spec/learnwords2/LWdbSpec.js:70:18)
  Message:
    ReferenceError: questions is not defined
  Stack:
    ReferenceError: questions is not defined
        at Object.<anonymous> (/home/user8/Documents/LearnWords2/spec/learnwords2/LWdbSpec.js:76:12)
````

In  [LWdbSpec.js](https://github.com/hhzl/LearnWords2/blob/master/spec/learnwords2/LWdbSpec.js)  we have
````JavaScript 

var LWdb = require('../../src/LWdb');
var BoxOfQuestions = require('../../src/BoxOfQuestions');
....

describe("LearnWords2 - App model", function() {

describe("BoxOfQuestions", function() {
  var db;


  beforeEach(function() {
    questions  = new BoxOfQuestions("LWquestions");
  });


  it("should be able to create a BoxOfQuestions object", function() {

    expect(questions).not.toBe(null);
    expect(questions).not.toBe(undefined);

      });
````
